// flow-typed signature: 3ddef4b61a980fce502b0ec2b73ae0ef
// flow-typed version: <<STUB>>/webpack-get-code-on-done_v^1.0.12/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-get-code-on-done'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-get-code-on-done' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-get-code-on-done/src/index' {
  declare module.exports: any;
}

declare module 'webpack-get-code-on-done/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-get-code-on-done/src/index.js' {
  declare module.exports: $Exports<'webpack-get-code-on-done/src/index'>;
}
declare module 'webpack-get-code-on-done/tests/index.test.js' {
  declare module.exports: $Exports<'webpack-get-code-on-done/tests/index.test'>;
}
